language: c
env:
  global:
   # Encrypted COVERITY_SCAN_TOKEN
   - secure: "V624S2sinRh1pSqwlAJ5Ycz+pI9OhiWBhlUqCMyzncDc+VVwXNbcNhFuPpriE81PvCyo6cSyjRpk9/PtBd5TOKNGqj9FDUzdG4usIJT38vmwTyzhPsJaUCMhcFNdz7/ypfLzY5+g5h4oB4JuKlMI2S73EeFF6TAtJWyTW9eDKv4="
matrix:
  include:
  - compiler: clang
    os: linux
    dist: trusty
    sudo: required
    group: edge
    addons:
      coverity_scan:
        project:
          name: "libyal/libesedb"
          description: "Build submitted via Travis CI"
        notification_email: joachim.metz@gmail.com
        build_command_prepend: "./synclibs.sh && ./autogen.sh && ./configure"
        build_command: "make -j4"
        branch_pattern: master
  - compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - compiler: clang
    os: osx
    osx_image: xcode8.1
  - compiler: gcc
    os: osx
    osx_image: xcode8.1
before_install:
  - if test ${TRAVIS_OS_NAME} = "linux"; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi
  - if test ${TRAVIS_OS_NAME} = "linux"; then sudo apt-get update && sudo apt-mark hold oracle-java9-installer postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 postgresql-client postgresql-client-common postgresql-common postgresql-contrib-9.2 postgresql-contrib-9.3 postgresql-contrib-9.4 postgresql-contrib-9.5 postgresql-contrib-9.6 postgresql-doc && sudo apt-get --fix-missing -o Dpkg::Options::="--force-confold" upgrade -y && sudo apt-get install -y autopoint; fi
  - if test ${TRAVIS_OS_NAME} = "osx"; then brew update && brew install gettext gnu-sed && brew link --force gettext; fi
install:
  - if test ${TRAVIS_OS_NAME} = "osx"; then export SED="/usr/local/bin/gsed"; fi
  - ./synclibs.sh && ./autogen.sh
  - if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
script:
  - if test ${TRAVIS_OS_NAME} = "linux"; then export PATH=$(echo $PATH | tr ":" "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s/::/:/g"); fi
  - ./runtests.sh
after_success:
  - if test ${TRAVIS_OS_NAME} = "linux" && test ${CC} = "gcc"; then curl -o codecov.sh -s https://codecov.io/bash && /bin/bash ./codecov.sh; fi
