environment:
  matrix:
  - TARGET: vs2008
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 9.0
  - TARGET: vs2010
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 10.0
  - TARGET: vs2012
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 11.0
  - TARGET: vs2013
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 12.0
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VisualStudioVersion: 14.0
  - TARGET: cygwin
  - TARGET: mingw32
  - TARGET: mingw64

# TODO: add x64, fix issue: LNK1158: cannot run 'cvtres.exe'
platform:
- Win32

# TODO: add VSDebug
configuration:
- Release

install:
- cmd: git clone https://github.com/libyal/libyal.git && move libyal ..\

build_script:
- ps: .\synclibs.ps1
- ps: .\autogen.ps1
- cmd: if [%TARGET%]==[vs2008] (
    msbuild msvscpp\libesedb.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2010] (
    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2010 msvscpp\libesedb.sln &&
    msbuild vs2010\libesedb.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2012] (
    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2012 msvscpp\libesedb.sln &&
    msbuild vs2012\libesedb.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2013] (
    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2013 msvscpp\libesedb.sln &&
    msbuild vs2013\libesedb.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2015] (
    C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2015 msvscpp\libesedb.sln &&
    msbuild vs2015\libesedb.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[cygwin] (
    xcopy /q /s C:\projects\libesedb C:\cygwin\home\appveyor\ &&
    C:\cygwin\bin\bash -e -l -c "cd libesedb" &&
    C:\cygwin\bin\bash -e -l -c "./synclibs.sh && ./autogen.sh" &&
    C:\cygwin\bin\bash -e -l -c "./configure && make -j4" )
- cmd: if [%TARGET%]==[mingw32] (
    xcopy /q /s C:\projects\libesedb C:\msys64\home\appveyor\ &&
    C:\msys64\usr\bin\bash -e -l -c "cd libesedb" &&
    C:\msys64\usr\bin\bash -e -l -c "./synclibs.sh && ./autogen.sh" &&
    C:\msys64\usr\bin\bash -e -l -c "./configure --host=i686-w64-mingw32 && make -j4" )
- cmd: if [%TARGET%]==[mingw64] (
    xcopy /q /s C:\projects\libesedb C:\msys64\home\appveyor\ &&
    C:\msys64\usr\bin\bash -e -l -c "cd libesedb" &&
    C:\msys64\usr\bin\bash -e -l -c "./synclibs.sh && ./autogen.sh" &&
    C:\msys64\usr\bin\bash -e -l -c "./configure --host=x86_64-w64-mingw32 && make -j4" )

test_script:
- cmd: rem Run tests
- ps: if ($env:TARGET -eq "vs2008") {
    .\runtests.ps1 }
- ps: if ($env:TARGET -eq "vs2010") {
    .\runtests.ps1 }
- ps: if ($env:TARGET -eq "vs2012") {
    .\runtests.ps1 }
- ps: if ($env:TARGET -eq "vs2013") {
    .\runtests.ps1 }
- ps: if ($env:TARGET -eq "vs2015") {
    .\runtests.ps1 }

