# Build from source on FreeBSD.
name: build_freebsd
on: [push]
permissions: read-all
jobs:
  build_freebsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Building from source
      id: build_freebsd
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        mem: 4096
        # Note that the test scripts require bash
        prepare: |
          pkg install -y autoconf automake bash gettext git libtool pkgconf
        run: |
          tests/build.sh
          tests/runtests.sh
